=== LaibahA/tensile-test-data-annotation/tensile_test_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "sample": {"type": "string", "minLength": 1},
        "date": {"type": "string", "format": "date"},
        "material": {"type": "string"},
        "units": {
            "type": "object",
            "properties": {
                "width": {"type": "string"},
                "thickness": {"type": "string"},
                "length": {"type": "string"},
                "elongation": {"type": "string"},
                "force": {"type": "string"}
            },
            "required": ["width", "thickness", "length", "elongation", "force"]
        },

        "geometry": {
            "type": "object",
            "properties": {
                "width": {"type": "number"},
                "thickness": {"type": "number"},
                "length": {"type": "number"}
            },
            "required": ["width", "thickness", "length"]
        },

        "youngs_modulus": {
            "type": "object",
            "properties": {
                "value": {"type": "number"},
                "reference": {"type": "string"},
                "units": {"type": "string"}
            },
            "required": ["value", "units"]
        },

        "yield_strength": {
            "type": "object",
            "properties": {
                "value": {"type": "number"},
                "reference": {"type": "string"},
                "units": {"type": "string"}
            },
            "required": ["value", "units"]
        },

        "strain_at_fracture": {
            "type": "object",
            "properties": {
                "value": {"type": "number"},
                "reference": {"type": "string"},
                "units": {"type": "string"}
            },
            "required": ["value"]
        },

        "raw_data": {
            "type": "object",
            "properties": {
                "force": {
                    "type": "array",
                    "items": {"type": "number"},
                    "minItems": 1
                },
                "elongation": {
                    "type": "array",
                    "items": {"type": "number"},
                    "minItems": 1
                }
            },
            "required": ["force", "elongation"]
        }
    },

    "required": [
        "sample",
        "material",
        "units",
        "geometry",
        "youngs_modulus",
        "yield_strength",
        "strain_at_fracture",
        "raw_data"
    ]
}

=== LaibahA/tensile-test-data-annotation/demo/importedData/jsonFiles/Sample_Input.json
{
    "date": "2025-10-1",
    "sample": "Sample Input",
    "material": "Sample Material",
    "units": {
        "width": "mm",
        "thickness": "mm",
        "elongation": "mm",
        "length": "mm",
        "force": "N",
        "strain": "mm/mm",
        "stress": "MPa"
    },
    "geometry": {
        "width": 13.54,
        "thickness": 3.15,
        "length": 50.0
    },
    "raw_data": {
        "elongation": [
            -4.5076951948885835e-05,
            -3.7488653958916984e-05,
            6.453916512327851e-05,
            9.465146888487652e-05,
            -2.243222496645103e-05
        ],
        "force": [
            -0.2827690541744232,
            -6.269662857055664,
            -6.8461480140686035,
            -2.5180535316467285,
            -6.9750895500183105
        ]
    },
    "youngs_modulus": {
        "value": 76443.93,
        "units": "MPa",
        "reference": "ASTM D638-22: A2.4 Modulus of Elasticity"
    },
    "yield_strength": {
        "value": 253.19,
        "units": "MPa",
        "reference": "ASTM D638-22: A2.6 Offset Yield Strength"
    },
    "strain_at_fracture": {
        "value": 0.14,
        "units": "mm/mm",
        "reference": "ASTM D638-22: A2.24 and A2.25"
    }
}
